version: "3.1"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: micro-auth-prod-app
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - JAVA_OPTS_APPEND=-Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled
      - DB_VENDOR=h2
    ports:
      - 8080:8080
    networks:
      default:
        aliases:
          - app.test

  test:
    build: 
      context: ./tests
      args:
        - UID=${UID}
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-auth-test
    tty: true
    volumes:
      - ./tests:/home/node/app
    networks:
      - default
    
  selenium:
    image: selenium/standalone-chrome:91.0-chromedriver-91.0-20210527
    container_name: micro-auth-selenium
    expose:
      - 4444
    networks:
      - default

  dockerize:
    image: jwilder/dockerize
    container_name: micro-auth-dockerize
    entrypoint: dockerize -wait tcp://app.test:8080 -timeout 200s
    depends_on:
      - app
    networks:
      - default

networks:
  default:
    driver: bridge