apiVersion: skaffold/v1
kind: Config
metadata:
  name: dev-k8s-keycloak
build:
  local:
    push: false
  # artifacts:
  #   - image: newerton/keycloak
  #     context: .
  #     docker:
  #       dockerfile: Dockerfile
  #     sync:
  #       manual:
  #         - src: 'src/**/*.*'
  #           dest: .
deploy:
  # kubeContext: docker-desktop
  kubectl:
    flags:
      global: [--namespace=nestjs-k8s-namespace]
    manifests:
      - ./k8s/01-secrets.yaml
      - ./k8s/02-configmap-import.json.yaml
      - ./k8s/02-configmap-standalone-ha.xml.yaml
      - ./k8s/03-mysql.yaml
      - ./k8s/04-app.yaml
